### ISSUE TITLE
Overwrote entire system partition

### ISSUE THREAD

**Issue by loops** [virt-manager/virt-bootstrap#7]
Unable to go back and retrace my steps now, but somehow I managed to overwrite my entire
Fedora root partition with a docker image download of Ubuntu.  Obviously the system was completely trashed and in need of a reinstall.   This was all my fault, as I was just playing around with things without doing a lot of prior research, but it would be nice if the tool protected people like me from myself :-)

Consider refusing to unpack a docker container in the root partition.  I don't think there is a valid use case where it would be a desirable option.

Cheers.

**Comment by rst0git** [comment]
@loops Thank you for reporting this issue. I sent a patch to the mailing list
https://www.redhat.com/archives/virt-tools-list/2019-January/msg00009.html

**Comment by rst0git** [comment]
cc: @cbosdo
